name = "Advanced Combat Medicine 1.1.1";
tooltip = "Advanced Combat Medicine";
picture = "logo.paa";
logo = "logo_small.paa";
description = "Advanced Combat Medicine";
author = "Blue";
actionName = "Discord";
action = "https://discord.gg/5MNPpBpsEr/";
overview = "Advanced Combat Medicine is an expansion of ACE Medical, introducing many missing considerations for casualty care during ops.";