#define COMPONENT cbrn
#define COMPONENT_BEAUTIFIED CBRN
#include "\x\ACM\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE

#ifdef DEBUG_ENABLED_CBRN
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_CBRN
    #define DEBUG_SETTINGS DEBUG_SETTINGS_CBRN
#endif

#include "\x\ACM\addons\main\script_macros.hpp"

// UI grid
#define SIZEX ((safeZoneW / safeZoneH) min 1.2)
#define SIZEY (SIZEX / 1.2)
#define W_PART(num) (num * (SIZEX / 40))
#define H_PART(num) (num * (SIZEY / 25))
#define X_PART(num) (W_PART(num) + (safeZoneX + (safeZoneW - SIZEX) / 2))
#define Y_PART(num) (H_PART(num) + (safeZoneY + (safeZoneH - SIZEY) / 2))

#define IDC_MODULE_CREATE_HAZARDZONE                   100000
#define IDC_MODULE_CREATE_HAZARDZONE_LIST              100001
#define IDC_MODULE_CREATE_HAZARDZONE_RADIUS            100002
#define IDC_MODULE_CREATE_HAZARDZONE_SHOWMIST          100003
#define IDC_MODULE_CREATE_HAZARDZONE_ATTACH            100004
#define IDC_MODULE_CREATE_HAZARDZONE_EFFECTTIME        100005
#define IDC_MODULE_CREATE_HAZARDZONE_AFFECTAI          100006

#define IDC_MODULE_CREATE_CHEMICALDEVICE               100010
#define IDC_MODULE_CREATE_CHEMICALDEVICE_LIST          100011
#define IDC_MODULE_CREATE_CHEMICALDEVICE_RADIUS        100012
#define IDC_MODULE_CREATE_CHEMICALDEVICE_PERMANENT     100013
#define IDC_MODULE_CREATE_CHEMICALDEVICE_ATTACH        100014
#define IDC_MODULE_CREATE_CHEMICALDEVICE_AFFECTAI      100015
#define IDC_MODULE_CREATE_CHEMICALDEVICE_CLOUDSIZELIST 100016