PREP(canConvert);
PREP(convertCasualty);
PREP(convertCasualtyAction);
PREP(defineReinforcePoint);
PREP(defineEvacuationPoint);
PREP(getAvailableTickets);
PREP(initUnit);
PREP(onRespawn);
PREP(setCasualtyTicket);