name = "Advanced Combat Medicine"
author = "Blue"
prefix = "ACM"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
	"logo.paa",
    "logo_small.paa"
]

[version]
git_hash = 0

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
    "1779063631", # Zeus Enhanced
    "2369477168" # Advanced Dev Tools
]