PREP(clearPatients);
PREP(createCustomBloodTypeList);
PREP(initHealTent);
PREP(initTrainingComputer);
PREP(generatePatient);
PREP(generatePatients);
PREP(spawnCustomPatient);
PREP(spawnPatient_childActions);
PREP(spawnPatients_childActions);