#include "\a3\ui_f\hpp\defineCommonGrids.inc"

#define IDC_STETHOSCOPE 81000
#define IDC_STETHOSCOPE_TEXT 81001
#define IDC_STETHOSCOPE_BELL 81002

#define IDC_STETHOSCOPE_RIGHTSIDE 81003
#define IDC_STETHOSCOPE_LEFTSIDE 81004

#define IDC_STETHOSCOPE_RIGHTLUNG_SPACE 81010
#define IDC_STETHOSCOPE_RIGHTLUNG_SPACE_2 81011
#define IDC_STETHOSCOPE_LEFTLUNG_SPACE 81012
#define IDC_STETHOSCOPE_LEFTLUNG_SPACE_2 81013

#define IDC_STETHOSCOPE_RIGHTLUNG_BRONCHIAL 81014
#define IDC_STETHOSCOPE_RIGHTLUNG_BRONCHOVESTICULAR 81015
#define IDC_STETHOSCOPE_RIGHTLUNG_VESTICULAR_MIDDLE 81016
#define IDC_STETHOSCOPE_RIGHTLUNG_VESTICULAR_LOWER 81017

#define IDC_STETHOSCOPE_LEFTLUNG_BRONCHIAL 81019
#define IDC_STETHOSCOPE_LEFTLUNG_BRONCHOVESTICULAR 81020
#define IDC_STETHOSCOPE_LEFTLUNG_VESTICULAR_MIDDLE 81021
#define IDC_STETHOSCOPE_LEFTLUNG_VESTICULAR_LOWER 81022

#define IDC_STETHOSCOPE_HEART_1 81030
#define IDC_STETHOSCOPE_HEART_2 81031
#define IDC_STETHOSCOPE_HEART_3 81032
#define IDC_STETHOSCOPE_HEART_4 81033
#define IDC_STETHOSCOPE_HEART_CENTER 81034

#define IDC_STETHOSCOPE_BONE_STERNUM 81040

#define ACM_STETHOSCOPE_POS_X(N) (N * GUI_GRID_W + GUI_GRID_CENTER_X)
#define ACM_STETHOSCOPE_POS_Y(N) (N * GUI_GRID_H + GUI_GRID_CENTER_Y)
#define ACM_STETHOSCOPE_POS_W(N) (N * GUI_GRID_W)
#define ACM_STETHOSCOPE_POS_H(N) (N * GUI_GRID_H)
#define ACM_STETHOSCOPE_BG_POS_X_CENTER(N) (ACM_STETHOSCOPE_POS_X(20) - (ACM_STETHOSCOPE_POS_W(N) / 2))
#define ACM_STETHOSCOPE_BG_POS_Y_CENTER(N,Y) (ACM_STETHOSCOPE_POS_Y(Y) - (ACM_STETHOSCOPE_POS_H(N) / 2))