#include "\a3\ui_f\hpp\defineCommonGrids.inc"

#define IDC_FEELPULSE 80000
#define IDC_FEELPULSE_TEXT 80001
#define IDC_FEELPULSE_HEART 80002

#define ACM_FEELPULSE_FRONT_X 19.53
#define ACM_FEELPULSE_FRONT_Y 12.15
#define ACM_FEELPULSE_FRONT_W 1
#define ACM_FEELPULSE_FRONT_H 0.75

#define ACM_FEELPULSE_POS_X(N) (N * GUI_GRID_W + GUI_GRID_CENTER_X)
#define ACM_FEELPULSE_POS_Y(N) (N * GUI_GRID_H + GUI_GRID_CENTER_Y)
#define ACM_FEELPULSE_POS_W(N) (N * GUI_GRID_W)
#define ACM_FEELPULSE_POS_H(N) (N * GUI_GRID_H)

#define ACM_FEELPULSE_POS_X_CENTER(N) (ACM_FEELPULSE_POS_X(20) - (ACM_FEELPULSE_POS_W(N) / 2))
#define ACM_FEELPULSE_POS_Y_CENTER(N) (ACM_FEELPULSE_POS_Y(12.5) - (ACM_FEELPULSE_POS_H(N) / 2))