#include "\a3\ui_f\hpp\defineCommonGrids.inc"

#define IDC_MEASUREBP              82000
#define IDC_MEASUREBP_TEXT         82001
#define IDC_MEASUREBP_BUTTON_BULB  82002
#define IDC_MEASUREBP_BUTTON_VALVE 82003
#define IDC_MEASUREBP_STETHOSCOPE  82004
#define IDC_MEASUREBP_HEARTBACK    82005
#define IDC_MEASUREBP_HEART        82006
#define IDC_MEASUREBP_DIAL_1       82101
#define IDC_MEASUREBP_DIAL_2       82102

#define MEASUREBP_INTERACTABLE_SCALE 0.45

#define ACM_MEASUREBP_GUI_GRID_W (safezoneW * 0.55)
#define ACM_MEASUREBP_GUI_GRID_H (ACM_MEASUREBP_GUI_GRID_W * 4/3)
#define ACM_MEASUREBP_GUI_GRID_X (safezoneX)
#define ACM_MEASUREBP_GUI_GRID_Y (safezoneY + (safezoneH - ACM_GUI_GRID_H) / 2)

#define ACM_MEASUREBP_pxToScreen_X(X) (X / 2048 * ACM_MEASUREBP_GUI_GRID_W + ACM_MEASUREBP_GUI_GRID_X)
#define ACM_MEASUREBP_pxToScreen_Y(X) (X / 2048 * ACM_MEASUREBP_GUI_GRID_H + ACM_MEASUREBP_GUI_GRID_Y)
#define ACM_MEASUREBP_pxToScreen_W(X) (X / 2048 * ACM_MEASUREBP_GUI_GRID_W)
#define ACM_MEASUREBP_pxToScreen_H(X) (X / 2048 * ACM_MEASUREBP_GUI_GRID_H)

#define MEASUREBP_INTERACTABLE_TOPLEFT_X 399
#define MEASUREBP_INTERACTABLE_TOPLEFT_Y 1195

#define MEASUREBP_DIAL_LENGTH 200