#include "\a3\ui_f\hpp\defineCommonGrids.inc"

#define IDC_MEASUREBP              82000
#define IDC_MEASUREBP_TEXT         82001
#define IDC_MEASUREBP_BUTTON_BULB  82002
#define IDC_MEASUREBP_BUTTON_VALVE 82003
#define IDC_MEASUREBP_STETHOSCOPE  82004
#define IDC_MEASUREBP_HEARTBACK    82005
#define IDC_MEASUREBP_HEART        82006
#define IDC_MEASUREBP_DIAL         82007

#define ACM_MEASUREBP_POS_X(N) (N * GUI_GRID_W + GUI_GRID_CENTER_X)
#define ACM_MEASUREBP_POS_Y(N) (N * GUI_GRID_H + GUI_GRID_CENTER_Y)
#define ACM_MEASUREBP_POS_W(N) (N * GUI_GRID_W)
#define ACM_MEASUREBP_POS_H(N) (N * GUI_GRID_H)

#define ACM_MEASUREBP_POS_X_CENTER(N,X) (ACM_MEASUREBP_POS_X(X) - (ACM_MEASUREBP_POS_W(N) / 2))
#define ACM_MEASUREBP_POS_Y_CENTER(N,Y) (ACM_MEASUREBP_POS_Y(Y) - (ACM_MEASUREBP_POS_H(N) / 2))