#include "\a3\ui_f\hpp\defineCommonGrids.inc"

#define ACM_SYRINGEDRAW_POS_X(N) ((N * NORMALIZE_UISCALE) * GUI_GRID_W + GUI_GRID_CENTER_X / NORMALIZE_UISCALE)
#define ACM_SYRINGEDRAW_POS_Y(N) ((N * NORMALIZE_UISCALE) * GUI_GRID_H + GUI_GRID_CENTER_Y / NORMALIZE_UISCALE)
#define ACM_SYRINGEDRAW_POS_W(N) ((N * NORMALIZE_UISCALE) * GUI_GRID_W)
#define ACM_SYRINGEDRAW_POS_H(N) ((N * NORMALIZE_UISCALE) * GUI_GRID_H)

#define IDC_SYRINGEDRAW                          84000
#define IDC_SYRINGEDRAW_TEXT                     84001
#define IDC_SYRINGEDRAW_BOTTOMTEXT               84002
#define IDC_SYRINGEDRAW_BUTTON_DRAW              84003
#define IDC_SYRINGEDRAW_BUTTON_PUSH              84004
#define IDC_SYRINGEDRAW_BUTTON_INJECT            84005
#define IDC_SYRINGEDRAW_MEDLIST                  84006
#define IDC_SYRINGEDRAW_MEDLIST_SELECTION_BUTTON 84007
#define IDC_SYRINGEDRAW_MEDLIST_SELECTION_TEXT   84008
#define IDC_SYRINGEDRAW_PLUNGER                  84009
#define IDC_SYRINGEDRAW_SYRINGE_10_PLUNGER       84010
#define IDC_SYRINGEDRAW_SYRINGE_10_BACKBIT       84011
#define IDC_SYRINGEDRAW_SYRINGE_10_BARREL        84012
#define IDC_SYRINGEDRAW_SYRINGE_5_PLUNGER        84013
#define IDC_SYRINGEDRAW_SYRINGE_5_BACKBIT        84014
#define IDC_SYRINGEDRAW_SYRINGE_5_BARREL         84015
#define IDC_SYRINGEDRAW_SYRINGE_3_PLUNGER        84016
#define IDC_SYRINGEDRAW_SYRINGE_3_BACKBIT        84017
#define IDC_SYRINGEDRAW_SYRINGE_3_BARREL         84018
#define IDC_SYRINGEDRAW_SYRINGE_1_PLUNGER        84019
#define IDC_SYRINGEDRAW_SYRINGE_1_BACKBIT        84020
#define IDC_SYRINGEDRAW_SYRINGE_1_BARREL         84021

#define SYRINGEDRAW_MOUSE_X (safeZoneX + (safeZoneW / 2))

#define ACM_SYRINGEDRAW_POS_LM_X(N) ((N) * GUI_GRID_W + GUI_GRID_CENTER_X)
#define ACM_SYRINGEDRAW_POS_LM_Y(N) ((N) * GUI_GRID_H + GUI_GRID_CENTER_Y)
#define ACM_SYRINGEDRAW_POS_LM_W(N) ((N) * GUI_GRID_W)
#define ACM_SYRINGEDRAW_POS_LM_H(N) ((N) * GUI_GRID_H)

#define SYRINGEDRAW_LIMIT_10_TOP         (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(7.5))
#define SYRINGEDRAW_LIMIT_10_TOP_MOUSE   (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(7.52))
#define SYRINGEDRAW_LIMIT_10_BOTTOM      (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(18))
#define SYRINGEDRAW_10_Y_OFFSET          ((safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_LM_Y(21)) * NORMALIZE_UISCALE)
#define SYRINGEDRAW_LIMIT_5_TOP          (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(6.9))
#define SYRINGEDRAW_LIMIT_5_TOP_MOUSE    (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(6.92))
#define SYRINGEDRAW_LIMIT_5_BOTTOM       (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(17.2))
#define SYRINGEDRAW_5_Y_OFFSET           ((safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_LM_Y(20.42)) * NORMALIZE_UISCALE)
#define SYRINGEDRAW_LIMIT_3_TOP          (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(6.9))
#define SYRINGEDRAW_LIMIT_3_TOP_MOUSE    (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(6.92))
#define SYRINGEDRAW_LIMIT_3_BOTTOM       (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(16.73))
#define SYRINGEDRAW_3_Y_OFFSET           ((safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_LM_Y(20.42)) * NORMALIZE_UISCALE)
#define SYRINGEDRAW_LIMIT_1_TOP          (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(6.9))
#define SYRINGEDRAW_LIMIT_1_TOP_MOUSE    (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(6.92))
#define SYRINGEDRAW_LIMIT_1_BOTTOM       (safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_Y(17.1))
#define SYRINGEDRAW_1_Y_OFFSET           ((safeZoneY + (safeZoneH / 2) + ACM_SYRINGEDRAW_POS_LM_Y(20.42)) * NORMALIZE_UISCALE)