#include "\a3\ui_f\hpp\defineCommonGrids.inc"

#define IDC_TRANSFUSIONMENU 86000
#define IDC_TRANSFUSIONMENU_PATIENTNAME 86001
#define IDC_TRANSFUSIONMENU_SELECTIONTEXT 86002
#define IDC_TRANSFUSIONMENU_LISTPANEL 86003

#define IDC_TRANSFUSIONMENU_BG_IO_TORSO           86010
#define IDC_TRANSFUSIONMENU_BG_IV_RIGHTARM_UPPER  86020
#define IDC_TRANSFUSIONMENU_BG_IV_RIGHTARM_MIDDLE 86021
#define IDC_TRANSFUSIONMENU_BG_IV_RIGHTARM_LOWER  86022
#define IDC_TRANSFUSIONMENU_BG_IV_LEFTARM_UPPER   86023
#define IDC_TRANSFUSIONMENU_BG_IV_LEFTARM_MIDDLE  86024
#define IDC_TRANSFUSIONMENU_BG_IV_LEFTARM_LOWER   86025
#define IDC_TRANSFUSIONMENU_BG_IV_RIGHTLEG_UPPER  86026
#define IDC_TRANSFUSIONMENU_BG_IV_RIGHTLEG_MIDDLE 86027
#define IDC_TRANSFUSIONMENU_BG_IV_RIGHTLEG_LOWER  86028
#define IDC_TRANSFUSIONMENU_BG_IV_LEFTLEG_UPPER   86029
#define IDC_TRANSFUSIONMENU_BG_IV_LEFTLEG_MIDDLE  86030
#define IDC_TRANSFUSIONMENU_BG_IV_LEFTLEG_LOWER   86031